### ISSUE TITLE
The test debug_test.py cannot be run on Python 2, due to the Python 3 only extra arg ('ascii') to str.

### ISSUE THREAD

**Issue by JamesParrott** [fiftysevendegreesofrad/sdna_plus#13]
debug_test.py might have been intended to be a Python 3 only test.  But it can easily be made to run in Python 2 too.

To reproduce, install sDNA 4.1.1, and numpy in a Python 2 virtualenv, and in \sdna_plus\sDNA\sdna_vs2008\tests, run:

```
set "SDNADLL=c:\Program Files (x86)\sDNA\x64\sdna_vs2008.dll" & python -u debug_test.py
```

results in (~100 lines omitted):

```
PartialEdge test
ANGULAR, CENTRE ON CORNER
full traversal
half traversal ending exactly on centre
quarter traversal starting from centre
EUCLIDEAN, CENTRE ON CORNER

...


ERROR: in formula for link metric
1+*)
Unexpected operator "*" found at position 2
1+*): threw config exception Error in formula for link metric
5.7723*ang+69.3*euc+0.77*hg+1000*hl: fwd=3001.45 bwd=2002.22
sin(90): fwd=0.893997 bwd=0.893997 TESTED NONLINEAR
sin(pi/2): fwd=1 bwd=1 TESTED NONLINEAR
ERROR: in formula for link metric

Expression is empty.
: threw config exception Error in formula for link metric


Choice Test, Angular analysis, discrete space, unweighted
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "debug_test.py", line 29, in warning
    print(str(x,"ascii"))
TypeError: str() takes at most 1 argument (2 given)
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "debug_test.py", line 29, in warning
    print(str(x,"ascii"))
TypeError: str() takes at most 1 argument (2 given)
calc created with config start_gs=start_gs;end_gs=end_gs;weight=weight;probroutes;outputsums;radii=5,6,10,50,63,n;metric=ANGULAR;cont=False;weight_type=link;ignorenonlinear;
Traceback (most recent call last):
  File "debug_test.py", line 263, in <module>
    test_net_all_options("Choice Test",choice_test,choice_test_radii,12,True)
  File "debug_test.py", line 203, in test_net_all_options
    test_net(net_definition,euclidean_radii,ANGULAR,False,False,problink)
  File "debug_test.py", line 157, in test_net
    names = [str(x,"ascii") for x in names[0:outlength]]
TypeError: str() takes at most 1 argument (2 given)
```

Expected (output from the same in a Python 3 venv), several thousand lines omitted:

```
(pytest_py312) %userprofile%\Coding\repos\sdna_plus\sDNA\sdna_vs2008\tests>set "SDNADLL=c:\Program Files (x86)\sDNA\x64\sdna_vs2008.dll" & python -u debug_test.py
PartialEdge test
ANGULAR, CENTRE ON CORNER
full traversal
half traversal ending exactly on centre
quarter traversal starting from centre
EUCLIDEAN, CENTRE ON CORNER
full traversal
half traversal ending exactly on centre
quarter traversal starting from centre
ANGULAR, CENTRE ON STRAIGHT
full traversal
half traversal ending exactly on centre
quarter traversal starting from centre
EUCLIDEAN, CENTRE ON STRAIGHT
full traversal
half traversal ending exactly on centre
quarter traversal starting from centre
EUCLIDEAN ASYMMETRIC
full traversal
half traversal ending exactly on centre
quarter traversal starting from centre

muparser test
(0,0,0)(1,0,1)(1,3,-1)
ang/FULLang: fwd=1 bwd=1
euc/FULLeuc: fwd=1 bwd=1
hg/FULLhg: fwd=1 bwd=1
hl/FULLhl: fwd=1 bwd=1
one+two: fwd=3 bwd=3 TESTED NONLINEAR
ERROR:  Data field 'nonexistantvariable' not found on net.
nonexistantvariable: did not compile
ang: fwd=113.093 bwd=113.093
euc: fwd=5.01976 bwd=5.01976
hg: fwd=1 bwd=2
hl: fwd=2 bwd=1
hg+2.2*(hl+1.01): fwd=7.622 bwd=6.422 TESTED NONLINEAR

...

SumGeoLen Euc R12                  4  6  33.3333  33.3333
MeanGeoLen Euc R12                 4  6  33.3333  33.3333
Sum Crow Flight R12                1.94365  1.94365  33.3333  33.3333
Mean Crow Flight R12               1.94365  1.94365  33.3333  33.3333
Diversion Ratio Euc R12            2.05798  3.08697  1  1
Convex Hull Area R12               8.5  17.5  0  0
Convex Hull Perimeter R12          13.8863  22.2161  200  200
Convex Hull Max Radius R12         3.16228  9  50  50
Convex Hull Bearing R12            108.435  270  180  270
Convex Hull Shape Index R12        1.80529  2.24434  inf  inf
Problem route weight R12           0  0  0  0
Problem route excess R12           0  0  0  0
Sum Euc Dist R20                   4  6  33.3333  33.3333
Mean Euc Dist R20                  4  6  33.3333  33.3333
NetQuantPD Euc R20                 0.25  0.166667  0.03  0.03
Betweenness Euc R20                0.333333  0.333333  0.333333  0.333333
TPBetweenness Euc R20              0.333333  0.333333  0.333333  0.333333
TPDestination R20                  1  1  1  1
Links R20                          1  1  1  1
Length R20                         12  18  100  100
Ang Dist R20                       810  270  0  0
Weight R20                         1  1  1  1
Junctions R20                      2  2  0  0
Connectivity R20                   6  6  0  0
SumGeoLen Euc R20                  4  6  33.3333  33.3333
MeanGeoLen Euc R20                 4  6  33.3333  33.3333
Sum Crow Flight R20                1.94365  1.94365  33.3333  33.3333
Mean Crow Flight R20               1.94365  1.94365  33.3333  33.3333
Diversion Ratio Euc R20            2.05798  3.08697  1  1
Convex Hull Area R20               8.5  17.5  0  0
Convex Hull Perimeter R20          13.8863  22.2161  200  200
Convex Hull Max Radius R20         3.16228  9  50  50
Convex Hull Bearing R20            108.435  270  180  270
Convex Hull Shape Index R20        1.80529  2.24434  inf  inf
Problem route weight R20           0  0  0  0
Problem route excess R20           0  0  0  0
Sum Euc Dist R100                  19  21  33.3333  33.3333
Mean Euc Dist R100                 9.5  10.5  33.3333  33.3333
NetQuantPD Euc R100                0.316667  0.233333  0.03  0.03
Betweenness Euc R100               1.33333  1.33333  0.333333  0.333333
TPBetweenness Euc R100             0.666667  0.666667  0.333333  0.333333
TPDestination R100                 1  1  1  1
Links R100                         2  2  1  1
Length R100                        30  30  100  100
Ang Dist R100                      1080  1080  0  0
Weight R100                        2  2  1  1
Junctions R100                     2  2  1  1
Connectivity R100                  6  6  3  3
SumGeoLen Euc R100                 19  21  33.3333  33.3333
MeanGeoLen Euc R100                9.5  10.5  33.3333  33.3333
Sum Crow Flight R100               9.22376  9.22376  33.3333  33.3333
Mean Crow Flight R100              4.61188  4.61188  33.3333  33.3333
Diversion Ratio Euc R100           2.0592  2.57369  1  1
Convex Hull Area R100              25  25  0  0
Convex Hull Perimeter R100         24.3852  24.3852  200  200
Convex Hull Max Radius R100        8.24621  9.48683  50  50
Convex Hull Bearing R100           75.9638  251.565  180  270
Convex Hull Shape Index R100       1.89279  1.89279  inf  inf
Problem route weight R100          0  0  0  0
Problem route excess R100          0  0  0  0
Sum Euc Dist R126                  131  139  148.333  148.333
Mean Euc Dist R126                 32.75  34.75  49.4444  49.4444
NetQuantPD Euc R126                0.352381  0.267232  0.0648063  0.0648063
Betweenness Euc R126               3.33333  3.33333  2.33333  2.33333
TPBetweenness Euc R126             0.916667  0.916667  0.694444  0.694444
TPDestination R126                 1.16667  1.16667  0.833333  0.833333
Links R126                         4  4  3  3
Length R126                        230  230  130  130
Ang Dist R126                      1080  1080  1080  1080
Weight R126                        4  4  3  3
Junctions R126                     2  2  2  2
Connectivity R126                  6  6  6  6
SumGeoLen Euc R126                 131  139  148.333  148.333
MeanGeoLen Euc R126                32.75  34.75  49.4444  49.4444
Sum Crow Flight R126               114.272  106.125  136.175  132.44
Mean Crow Flight R126              28.5679  26.5313  45.3918  44.1468
Diversion Ratio Euc R126           1.56273  1.89715  1.07915  1.1121
Convex Hull Area R126              5407.5  5407.5  525  172.5
Convex Hull Perimeter R126         355.085  355.085  214.884  213.047
Convex Hull Max Radius R126        103.005  100.404  53.2353  55.0818
Convex Hull Bearing R126           90.5563  354.857  174.611  273.122
Convex Hull Shape Index R126       1.85549  1.85549  6.99904  20.9389
Problem route weight R126          0  0  0  0
Problem route excess R126          0  0  0  0


destroying
done
```

The background to this is, I'm currently running sDNA's tests in Pytest and subprocess.check_output: 
https://github.com/JamesParrott/sdna_plus/blob/Run_tests_with_pytest/sDNA/sdna_vs2008/tests/pytest/test_gathering_windows_command_line_tests.py

It's not much code, and other test runners or home brewed code will work just fine, but I've gathered the test commands from the batch files, and provided them as a parametrised test using Pytest's decorator, and Pytest's output reports are very nice..  

### Goal 3 (long term):  Support Linux 

One of the long term goals is moving to gcc, and hopefully porting to Linux.  How would it be known if sDNA works on Linux without running tests on that platform.  This Pytest code will happily run on Linux - it's abstracted out the batch files (and the test commands would run too, without much extra work - I've trimmed off the cmd specific stuff like `> nul` and 2&>1` which can be put back in by subprocess pipes).

### Goal 4 (medium term):  Moving to Python 3.
Pytest can systematically run all the tests against multiple Python versions in CI.  If all the tests pass in Python 3, there will be the same level of confidence for the sDNA manual to mention "has been tested on Python 3",  as that behind it mentioning "has been tested on Python 2.6. and 2.7".  So even though the focus is on every test passing on Python 3, it would also be good for all the tests to run in Python 2 as a control, giving a comprehensive comparison.  

If some tests don't run in Python 2, it'll only be possible to provide an incomplete comparison.  As anything like `debug_test.py` that has a Python2/3 incompatibility that's easy to fix, must be skipped or marked as a conditional expected failure.

**Comment by JamesParrott** [comment]
Fixed by 80b2bff14e013316b70e8d1a7ac83b5bb911903d
